# Generated by Django 4.0.6 on 2022-07-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_token',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_amount',
        ),
    ]
